basic:
    name: 'https://www.opploans.com batch 10'
    environments:
        production: 'https://www.opploans.com'
        staging: ''
        development: ''
    breakpoints:
        - 640
        - 1024
        - 1200
    pages:
        - /faqs/im-a-previous-opploans-customer-but-i-have-moved-to-a-different-state-can-i-still-apply
        - /faqs/finwise-bank-loan-opploans-loan
        - /faqs/relationship-opploans-finwise-bank
        - /faqs/who-do-i-work-with-if-i-am-approved
        - /faqs/how-can-i-get-a-personal-loan-online
        - /faqs/what-is-an-installment-loan
        - /faqs/what-is-a-personal-loan
        - /personal-loans-in-florida
        - /springfour
        - /myoffer
    monitoring:
        days: {  }
        type: daily
        schedule_time: '10:30 AM'
        schedule_time_zone: Europe/London
        compare_with: last-production
        compare_with_fresh: production
advanced:
    mask: ''
    remove: ''
    isolate: ''
    delay: 15
    scroll: true
    headers:
        - { header: '', value: '' }
    cookies: ''
    custom_js: ''
    custom_css: ''
    mock_content: ''
    performance:
        workers_production: 30
        workers_nonproduction: 10
        workers_production_delay: 0
        workers_nonproduction_delay: 0
    stabilize: true
